# Generated by Django 4.0 on 2022-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='quiz.Category'),
        ),
    ]
